repository:
  # A short description of the repository that will show up on GitHub
  description: Demo repository managed by safe-settings

  # Whether issues are enabled
  has_issues: true

  # Whether projects are enabled
  has_projects: true

  # Whether the wiki is enabled
  has_wiki: true

  # require pull request reviews before merging
  require_pull_request_reviews: true
  # Number of required approving reviews before merging
  required_approving_review_count: 1
